name: Tests
on: 
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        working-directory: client
        run: |
            if [[ -f "yarn.lock" ]]; then
              yarn install --frozen-lockfile
            else
             npm install
            fi
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: client
          build: CI='' npm run build
          start: npm start
